"""Initial migration - create all tables

Revision ID: 0d7ebab571f8
Revises: 
Create Date: 2025-11-18 12:41:08.232416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d7ebab571f8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_movies_tmdb_id', table_name='movies')
    op.create_index(op.f('ix_movies_tmdb_id'), 'movies', ['tmdb_id'], unique=False)
    op.create_index('idx_active_date', 'showtimes', ['is_active', 'showtime_date'], unique=False)
    op.create_index('idx_date_cinema', 'showtimes', ['showtime_date', 'cinema_id'], unique=False)
    op.create_index('idx_movie_date', 'showtimes', ['movie_id', 'showtime_date', 'is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_movie_date', table_name='showtimes')
    op.drop_index('idx_date_cinema', table_name='showtimes')
    op.drop_index('idx_active_date', table_name='showtimes')
    op.drop_index(op.f('ix_movies_tmdb_id'), table_name='movies')
    op.create_index('idx_movies_tmdb_id', 'movies', ['tmdb_id'], unique=False)
    # ### end Alembic commands ###
